#!/bin/sh
set -e

cat > /app/build/env-config.js <<EOF
window._env_ = {
  REACT_APP_BACKEND_URL: "${REACT_APP_BACKEND_URL:-}",
  REACT_APP_GEOSERVER_URL: "${REACT_APP_GEOSERVER_URL:-}",
  REACT_APP_BACKEND_KEY: "${REACT_APP_BACKEND_KEY:-}",
  REACT_APP_ENVIRONMENT: "${REACT_APP_ENVIRONMENT:-}",
  REACT_APP_BACKEND_BIAB_URL: "${REACT_APP_BACKEND_BIAB_URL:-}",
  REACT_APP_GA_TRACKING_ID: "${REACT_APP_GA_TRACKING_ID:-}",
  REACT_APP_YM_ID: "${REACT_APP_YM_ID:-}",
  REACT_APP_API_KEY: "${REACT_APP_API_KEY:-}",
  REACT_APP_DOMAIN: "${REACT_APP_DOMAIN:-}",
  REACT_APP_PROJECT_ID: "${REACT_APP_PROJECT_ID:-}",
  REACT_APP_STORAGE_BUCKET: "${REACT_APP_STORAGE_BUCKET:-}",
  REACT_APP_SENDER_ID: "${REACT_APP_SENDER_ID:-}",
  REACT_APP_APP_ID: "${REACT_APP_APP_ID:-}"
};
EOF

exec "$@"
