export const usersMock = [
  { id: 1, userName: "alejandro gomez" },
  { id: 2, userName: "mariana rodriguez" },
  { id: 3, userName: "juan perez dev" },
  { id: 4, userName: "catalina vargas" },
  { id: 5, userName: "andres felipa" },
  { id: 6, userName: "paula andrea sanchez" },
  { id: 7, userName: "carlos alberto diaz" },
  { id: 8, userName: "laura sofia castro" },
  { id: 9, userName: "miguel angel lopez" },
  { id: 10, userName: "isabella munoz" },
  { id: 11, userName: "santiago ramirez" },
  { id: 12, userName: "valeria gutierrez" },
  { id: 13, userName: "david fernandez" },
  { id: 14, userName: "angelica maria torres" },
  { id: 15, userName: "ricardo gonzalez qa" },
  { id: 16, userName: "yuliana martinez" },
  { id: 17, userName: "esteban cruz" },
  { id: 18, userName: "luisa fernanda blanco" },
  { id: 19, userName: "daniel enrique mora" },
  { id: 20, userName: "camila osorio" },
];
