name: Check format

on:
  push:
    branches:
      - feature/*
      - release/*

jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version-file: 'package.json'
        cache: pnpm
    - run: pnpm install
    - name: Run prettier
      run: pnpm check-format
      env:
        CI: true
