name: Deploy dev or stg

on:
  workflow_call:
    inputs:
      app_env:
        required: true
        type: string

env:
  AZURE_WEBAPP_NAME: biotablero-frontend
  REACT_APP_ENVIRONMENT:  ${{ inputs.config-app_env }}
  REACT_APP_BACKEND_BIAB_URL: ${{ vars.BACKEND_BIAB_URL }}
  REACT_APP_BACKEND_URL: ${{ vars.BACKEND_URL }}
  REACT_APP_BACKEND_KEY: ${{ secrets.BACKEND_KEY }}
  REACT_APP_GA_TRACKING_ID: ${{ vars.GA_TRACKING_ID }}

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: pnpm

      - name: install & build
        run: |
          pnpm -r install
          pnpm -r build-pkg
          pnpm install
          pnpm build

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
