name: Deploy develop

on:
  push:
    branches:
      - develop
      - feature/*
  workflow_dispatch:

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy_dev_stg.yml
    with:
      app_env: develop
