name: CI for releases

on:
  push:
    branches:
      - release/*

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version-file: '.nvmrc'
        cache: yarn
    - run: yarn install
    - name: Run prettier
      run: yarn run check-format
      env:
        CI: true
