name: Deploy staging

on:
  push:
    branches:
      - release/*
  workflow_dispatch:

jobs:
  call-deploy:
    uses: ./.github/workflows/deploy_dev_stg.yml
    with:
      app_env: staging
    secrets:
      BACKEND_KEY: ${{ secrets.BACKEND_KEY }}
      AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
